-- =========================================================
-- Hospitality Management System
-- schema/01_tables.sql
-- Oracle Database / PL-SQL Portfolio Project
-- =========================================================


-- =========================================================
-- 1. GUEST
-- =========================================================

CREATE TABLE guest (
    guest_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name      VARCHAR2(50)  NOT NULL,
    last_name       VARCHAR2(50)  NOT NULL,
    email           VARCHAR2(120),
    phone_number    VARCHAR2(25),
    date_of_birth   DATE,
    address_line    VARCHAR2(150),
    city            VARCHAR2(80),
    country         VARCHAR2(80),
    is_anonymized   CHAR(1) DEFAULT 'N' NOT NULL,
    anonymized_at   TIMESTAMP,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_guest
        PRIMARY KEY (guest_id),

    CONSTRAINT ck_guest_anonymized
        CHECK (is_anonymized IN ('Y', 'N'))
);


-- =========================================================
-- 2. ROOM TYPE
-- =========================================================

CREATE TABLE room_type (
    room_type_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    type_name      VARCHAR2(50)  NOT NULL,
    description    VARCHAR2(500),
    base_rate      NUMBER(10,2)  NOT NULL,
    max_occupancy  NUMBER(2)     NOT NULL,

    CONSTRAINT pk_room_type
        PRIMARY KEY (room_type_id),

    CONSTRAINT uq_room_type_name
        UNIQUE (type_name),

    CONSTRAINT ck_room_type_rate
        CHECK (base_rate >= 0),

    CONSTRAINT ck_room_type_occupancy
        CHECK (max_occupancy > 0)
);


-- =========================================================
-- 3. ROOM
-- =========================================================

CREATE TABLE room (
    room_id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    room_number         VARCHAR2(10) NOT NULL,
    room_type_id        NUMBER       NOT NULL,
    floor_number        NUMBER(3),
    operational_status  VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,

    CONSTRAINT pk_room
        PRIMARY KEY (room_id),

    CONSTRAINT uq_room_number
        UNIQUE (room_number),

    CONSTRAINT fk_room_room_type
        FOREIGN KEY (room_type_id)
        REFERENCES room_type(room_type_id),

    CONSTRAINT ck_room_status
        CHECK (
            operational_status IN (
                'AVAILABLE',
                'OCCUPIED',
                'CLEANING',
                'MAINTENANCE',
                'OUT_OF_SERVICE'
            )
        )
);


-- =========================================================
-- 4. AMENITY
-- =========================================================

CREATE TABLE amenity (
    amenity_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    amenity_name  VARCHAR2(80) NOT NULL,
    description   VARCHAR2(300),

    CONSTRAINT pk_amenity
        PRIMARY KEY (amenity_id),

    CONSTRAINT uq_amenity_name
        UNIQUE (amenity_name)
);


-- =========================================================
-- 5. ROOM AMENITY
-- =========================================================

CREATE TABLE room_amenity (
    room_id     NUMBER NOT NULL,
    amenity_id  NUMBER NOT NULL,

    CONSTRAINT pk_room_amenity
        PRIMARY KEY (room_id, amenity_id),

    CONSTRAINT fk_room_amenity_room
        FOREIGN KEY (room_id)
        REFERENCES room(room_id),

    CONSTRAINT fk_room_amenity_amenity
        FOREIGN KEY (amenity_id)
        REFERENCES amenity(amenity_id)
);


-- =========================================================
-- 6. HOTEL RESERVATION
-- =========================================================

CREATE TABLE hotel_reservation (
    reservation_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    guest_id            NUMBER       NOT NULL,
    check_in_date       DATE         NOT NULL,
    check_out_date      DATE         NOT NULL,
    total_guests        NUMBER(3)    NOT NULL,
    reservation_status  VARCHAR2(20) DEFAULT 'BOOKED' NOT NULL,
    booking_date        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_hotel_reservation
        PRIMARY KEY (reservation_id),

    CONSTRAINT fk_reservation_guest
        FOREIGN KEY (guest_id)
        REFERENCES guest(guest_id),

    CONSTRAINT ck_reservation_dates
        CHECK (check_out_date > check_in_date),

    CONSTRAINT ck_reservation_guests
        CHECK (total_guests > 0),

    CONSTRAINT ck_reservation_status
        CHECK (
            reservation_status IN (
                'BOOKED',
                'CANCELLED',
                'CHECKED_IN',
                'COMPLETED',
                'NO_SHOW'
            )
        )
);


-- =========================================================
-- 7. RESERVATION ROOM
-- =========================================================

CREATE TABLE reservation_room (
    reservation_room_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reservation_id       NUMBER       NOT NULL,
    room_id              NUMBER       NOT NULL,
    nightly_rate         NUMBER(10,2) NOT NULL,
    occupants            NUMBER(2)    NOT NULL,

    CONSTRAINT pk_reservation_room
        PRIMARY KEY (reservation_room_id),

    CONSTRAINT fk_res_room_reservation
        FOREIGN KEY (reservation_id)
        REFERENCES hotel_reservation(reservation_id),

    CONSTRAINT fk_res_room_room
        FOREIGN KEY (room_id)
        REFERENCES room(room_id),

    CONSTRAINT uq_reservation_room
        UNIQUE (reservation_id, room_id),

    CONSTRAINT ck_res_room_rate
        CHECK (nightly_rate >= 0),

    CONSTRAINT ck_res_room_occupants
        CHECK (occupants > 0)
);


-- =========================================================
-- 8. STAY
-- =========================================================

CREATE TABLE stay (
    stay_id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    reservation_id    NUMBER NOT NULL,
    actual_check_in   TIMESTAMP,
    actual_check_out  TIMESTAMP,
    stay_status       VARCHAR2(20) DEFAULT 'CHECKED_IN' NOT NULL,
    notes             VARCHAR2(500),

    CONSTRAINT pk_stay
        PRIMARY KEY (stay_id),

    CONSTRAINT uq_stay_reservation
        UNIQUE (reservation_id),

    CONSTRAINT fk_stay_reservation
        FOREIGN KEY (reservation_id)
        REFERENCES hotel_reservation(reservation_id),

    CONSTRAINT ck_stay_status
        CHECK (
            stay_status IN (
                'CHECKED_IN',
                'CHECKED_OUT'
            )
        )
);


-- =========================================================
-- 9. GUEST FOLIO
-- =========================================================

CREATE TABLE guest_folio (
    folio_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    stay_id       NUMBER NOT NULL,
    folio_status  VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,
    opened_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    closed_at     TIMESTAMP,

    CONSTRAINT pk_guest_folio
        PRIMARY KEY (folio_id),

    CONSTRAINT uq_folio_stay
        UNIQUE (stay_id),

    CONSTRAINT fk_folio_stay
        FOREIGN KEY (stay_id)
        REFERENCES stay(stay_id),

    CONSTRAINT ck_folio_status
        CHECK (
            folio_status IN (
                'OPEN',
                'CLOSED'
            )
        )
);


-- =========================================================
-- 10. FOLIO CHARGE
-- =========================================================

CREATE TABLE folio_charge (
    charge_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    folio_id      NUMBER        NOT NULL,
    charge_type   VARCHAR2(20)  NOT NULL,
    description   VARCHAR2(250) NOT NULL,
    amount        NUMBER(10,2)  NOT NULL,
    charge_date   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reference_id  NUMBER,

    CONSTRAINT pk_folio_charge
        PRIMARY KEY (charge_id),

    CONSTRAINT fk_charge_folio
        FOREIGN KEY (folio_id)
        REFERENCES guest_folio(folio_id),

    CONSTRAINT ck_charge_amount
        CHECK (amount >= 0),

    CONSTRAINT ck_charge_type
        CHECK (
            charge_type IN (
                'ROOM',
                'RESTAURANT',
                'MINIBAR',
                'SPA',
                'ROOM_SERVICE',
                'FEE',
                'OTHER'
            )
        )
);


-- =========================================================
-- 11. PAYMENT
-- =========================================================

CREATE TABLE payment (
    payment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    folio_id        NUMBER       NOT NULL,
    amount           NUMBER(10,2) NOT NULL,
    payment_method   VARCHAR2(20) NOT NULL,
    payment_status   VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL,
    payment_date     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_payment
        PRIMARY KEY (payment_id),

    CONSTRAINT fk_payment_folio
        FOREIGN KEY (folio_id)
        REFERENCES guest_folio(folio_id),

    CONSTRAINT ck_payment_amount
        CHECK (amount > 0),

    CONSTRAINT ck_payment_method
        CHECK (
            payment_method IN (
                'CREDIT_CARD',
                'DEBIT_CARD',
                'CASH',
                'MOBILE',
                'OTHER'
            )
        ),

    CONSTRAINT ck_payment_status
        CHECK (
            payment_status IN (
                'PENDING',
                'COMPLETED',
                'REFUNDED',
                'FAILED'
            )
        )
);


-- =========================================================
-- 12. RESTAURANT
-- =========================================================

CREATE TABLE restaurant (
    restaurant_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    restaurant_name  VARCHAR2(100) NOT NULL,
    location         VARCHAR2(100),
    opening_time     VARCHAR2(5),
    closing_time     VARCHAR2(5),

    CONSTRAINT pk_restaurant
        PRIMARY KEY (restaurant_id),

    CONSTRAINT uq_restaurant_name
        UNIQUE (restaurant_name)
);


-- =========================================================
-- 13. RESTAURANT TABLE
-- =========================================================

CREATE TABLE restaurant_table (
    table_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id   NUMBER       NOT NULL,
    table_number     VARCHAR2(10) NOT NULL,
    capacity         NUMBER(2)    NOT NULL,
    table_status     VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,

    CONSTRAINT pk_restaurant_table
        PRIMARY KEY (table_id),

    CONSTRAINT fk_table_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(restaurant_id),

    CONSTRAINT uq_restaurant_table
        UNIQUE (restaurant_id, table_number),

    CONSTRAINT ck_table_capacity
        CHECK (capacity > 0),

    CONSTRAINT ck_table_status
        CHECK (
            table_status IN (
                'AVAILABLE',
                'OCCUPIED',
                'RESERVED',
                'OUT_OF_SERVICE'
            )
        )
);


-- =========================================================
-- 14. RESTAURANT RESERVATION
-- =========================================================

CREATE TABLE restaurant_reservation (
    restaurant_reservation_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id              NUMBER        NOT NULL,
    guest_id                   NUMBER,
    table_id                   NUMBER,
    reservation_name           VARCHAR2(100) NOT NULL,
    phone_number               VARCHAR2(25),
    reservation_time           TIMESTAMP     NOT NULL,
    party_size                 NUMBER(2)     NOT NULL,
    reservation_status         VARCHAR2(20) DEFAULT 'BOOKED' NOT NULL,
    notes                      VARCHAR2(500),

    CONSTRAINT pk_restaurant_reservation
        PRIMARY KEY (restaurant_reservation_id),

    CONSTRAINT fk_rest_res_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(restaurant_id),

    CONSTRAINT fk_rest_res_guest
        FOREIGN KEY (guest_id)
        REFERENCES guest(guest_id),

    CONSTRAINT fk_rest_res_table
        FOREIGN KEY (table_id)
        REFERENCES restaurant_table(table_id),

    CONSTRAINT ck_rest_res_party_size
        CHECK (party_size > 0),

    CONSTRAINT ck_rest_res_status
        CHECK (
            reservation_status IN (
                'BOOKED',
                'SEATED',
                'COMPLETED',
                'CANCELLED',
                'NO_SHOW'
            )
        )
);


-- =========================================================
-- 15. MENU ITEM
-- =========================================================

CREATE TABLE menu_item (
    menu_item_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id  NUMBER        NOT NULL,
    item_name       VARCHAR2(100) NOT NULL,
    item_category   VARCHAR2(30)  NOT NULL,
    description     VARCHAR2(500),
    price           NUMBER(10,2)  NOT NULL,
    is_available    CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_menu_item
        PRIMARY KEY (menu_item_id),

    CONSTRAINT fk_menu_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(restaurant_id),

    CONSTRAINT ck_menu_price
        CHECK (price >= 0),

    CONSTRAINT ck_menu_available
        CHECK (is_available IN ('Y', 'N'))
);


-- =========================================================
-- 16. RESTAURANT ORDER
-- =========================================================

CREATE TABLE restaurant_order (
    order_id                   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id              NUMBER NOT NULL,
    table_id                   NUMBER,
    restaurant_reservation_id  NUMBER,
    folio_id                   NUMBER,
    payment_destination        VARCHAR2(20) DEFAULT 'DIRECT' NOT NULL,
    opened_at                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    closed_at                  TIMESTAMP,
    order_status               VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,

    CONSTRAINT pk_restaurant_order
        PRIMARY KEY (order_id),

    CONSTRAINT fk_order_restaurant
        FOREIGN KEY (restaurant_id)
        REFERENCES restaurant(restaurant_id),

    CONSTRAINT fk_order_table
        FOREIGN KEY (table_id)
        REFERENCES restaurant_table(table_id),

    CONSTRAINT fk_order_reservation
        FOREIGN KEY (restaurant_reservation_id)
        REFERENCES restaurant_reservation(restaurant_reservation_id),

    CONSTRAINT fk_order_folio
        FOREIGN KEY (folio_id)
        REFERENCES guest_folio(folio_id),

    CONSTRAINT ck_order_payment_destination
        CHECK (
            payment_destination IN (
                'DIRECT',
                'ROOM_CHARGE'
            )
        ),

    CONSTRAINT ck_order_status
        CHECK (
            order_status IN (
                'OPEN',
                'CLOSED',
                'VOID'
            )
        )
);


-- =========================================================
-- 17. ORDER ITEM
-- =========================================================

CREATE TABLE order_item (
    order_item_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    order_id       NUMBER       NOT NULL,
    menu_item_id   NUMBER       NOT NULL,
    quantity       NUMBER(3)    DEFAULT 1 NOT NULL,
    unit_price     NUMBER(10,2) NOT NULL,
    notes          VARCHAR2(250),

    CONSTRAINT pk_order_item
        PRIMARY KEY (order_item_id),

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES restaurant_order(order_id),

    CONSTRAINT fk_order_item_menu
        FOREIGN KEY (menu_item_id)
        REFERENCES menu_item(menu_item_id),

    CONSTRAINT ck_order_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_order_item_price
        CHECK (unit_price >= 0)
);